# Site
name: "David Coe Ph.D Candidate"
title: "Python and Climate Research"
description: ""
logo: 'https://daviology38.github.io/assets/images/logo.png'
favicon: 'https://daviology38.github.io/assets/images/logo.png'
#baseurl: ''
#google_analytics: 'UA-46278016-1'
include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 3
paginate_path: /page:num/
    
# Other
markdown: kramdown

# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "David_Coe@student.uml.edu"
  github: Daviology38
  twitter: Daviology38
#  medium: yourname
#  reddit: yourname
  linkedin: david-coe-7a042b129
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
#  ORCID: your ORCID ID
google-scholar: "citations?user=-XXxhtAAAAAJ&hl=en"


kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
